services:
  - type: web
    name: sahel-movies
    env: static
    staticPublishPath: ./
    buildCommand: ""
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
